import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import LoadingAnimation from "@/components/loading";
import {QueryClient} from "@tanstack/react-query";
import Providers from "@/components/react-query";
import {dehydrate} from "@tanstack/query-core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	const queryClient = new QueryClient();
	const dehydratedState = dehydrate(queryClient);
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <LoadingAnimation />
        <Providers dehydratedState={dehydratedState}>
	        {children}
        </Providers>
      </body>
    </html>
  );
}
